config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # ルートページ
  devise_for :users
  devise_scope :user do
    root :to => 'devise/sessions#new', as: :unauthenticated_root
  end

  # ユーザーアクション

  #検索機能
  get 'talkrooms/search', to: 'talk_rooms#search'

  #新規会員登録の時のルーティングエラーを修正
  get '/users', to: redirect("/user/sign_up")

  # ユーザー機能
  resources :users,             only: [:show, :edit, :update, :destroy] do
    resources :relationships,   only: [:create, :destroy]
    get :follows,   on: :member
    get :followers, on: :member
  end

  # 投稿機能
  resources :user_posts, only: [:new, :create, :index, :edit, :update, :destroy] do
    resources :post_comments, only: [:create, :update, :destroy]
  end

  # ルーム機能
  resources :talk_rooms do
    resources :room_media, only:  [:create, :update]
    resources :room_notes, only: [:create, :update, :destroy] do
      resources :room_note_media, only: [:create, :update]
    end
    resources :room_albums,     only: [:create, :update, :destroy]
    resources :room_events,     only: [:create, :update, :destroy]
    resource  :room_user,       only: [:index, :create, :destroy]
    resource  :room_favorites,  only: [:create, :destroy]
  end

  resources :talks,  only: [:create, :update]

  # 通知機能
  resources :notification, only: [:index]
end

app/models/talk_room.rb
class TalkRoom < ApplicationRecord

  has_many :room_users,       dependent: :destroy
  has_many :talk,             dependent: :destroy
  has_many :room_mediums,     dependent: :destroy
  has_many :room_note,        dependent: :destroy
  has_many :room_albums,      dependent: :destroy
  has_many :room_favorites,   dependent: :destroy
  has_many :room_events,      dependent: :destroy
  has_many :users,            through: :room_users

  has_one_attached :talk_room_image

  scope :recently, -> { order(updated_at: :desc) }
end

app/controllers/talk_rooms_controller.rb
class TalkRoomsController < ApplicationController

  def new
    @talk_room = TalkRoom.new
    @talk_room.room_users.new
  end

  def create
    @talk_room = TalkRoom.new(talk_room_params)
    @talk_room.save
  end

  def show
    @room = TalkRoom.find(params[:id])
    @talks = @room.talk
  end

  def index
    # 友だちがクリックされた時のルーム表示判定
    unless params[:follower].blank?
      @user = User.find_by(id: params[:follower])
      current_room = RoomUser.where(user_id: current_user.id)
      another_room = RoomUser.where(user_id: @user.id)
      unless @user.id == current_user.id
        current_room.each do |cr|
          another_room.each do |ar|
            # ルームが存在する時 かつ ルームのユーザーIDが2人まで（グループとの差別化）
            if cr.talk_room_id == ar.talk_room_id && TalkRoom.find_by(id: cr.talk_room_id).users.ids.size == 2
              @is_room = true
              @room = TalkRoom.find_by(id: cr.talk_room_id)
              @talks = @room.talk
            end
          end
        end
        # なければ新規作成
        unless @is_room
          @room = TalkRoom.create
          RoomUser.create(user_id: current_user.id, talk_room_id: @room.id)
          RoomUser.create(user_id: params[:follower].to_i, talk_room_id: @room.id)
        end
      end
    end

    # グループがクリックされた時のルーム判定
    unless params[:room_id].blank?
      @room = TalkRoom.find_by(id: params[:room_id])
      @talks = @room.talk
      @room_name = @room.room_name
    end

    # 知り合いかも？に自分以外のユーザーを表示
    @users = User.where.not(id: current_user.id)

    # # トークが新しい順にトークルームを並べる
    # if Talk.exists?
    #   latest_talk = Talk.from(Talk.order(created_at: :asc))
    #                     .group(:talk_room_id)
    #                     .select(:talk_room_id)
    #                     .order(created_at: :desc)
    #   @latest_talks = Array.new
    #   latest_talk.each do |talk|
    #     room = TalkRoom.find_by(id: talk.talk_room_id)
    #     unless room.users.where(id: current_user.id).blank?
    #       @latest_talks.push(room)
    #     end
    #   end
    # end

    #　自分が参加しているグループトークの表示
     # 自分が参加しているグループを探す
    current_user_entry_group = current_user.talk_room.where.not(room_name: :nill).pluck(:talk_room_id)
     # 名前順で並び替え
    @entry_room = TalkRoom.where(id: current_user_entry_group).order(room_name: :asc)
  end

  def edit
    # code
  end

  def update
    # code
  end

  def destroy

  end

  def search
    @users = current_user.followings.where('name LIKE(?)', "%#{params[:keyword]}%")
    respond_to do |format|
      format.html #htmlがないとエラーが出る
      format.json
    end
  end

  private

  def talk_room_params
    # ルーム作成時に自分のidが入るようにしておく
    params[:talk_room][:user_ids].push(current_user.id)
    # 配列の中身を全てintegerに
    params[:talk_room][:user_ids].map!(&:to_i)
    params[:talk_room].permit(:room_name, { user_ids: []})
  end
end

app/helpers/talk_rooms_helper.rb
module TalkRoomsHelper
end

app/views/talk_rooms/index.html.slim
.contain
  .talk-room-index
    .talk-room-index__sidebar
      .talk-room-index__sidebar--main
        span.tab-btn.is-show
          i(name="user" id="talk-room-user" class="fas fa-user")
          p.fukidashi 友達
        span.tab-btn
          i(name="comment" id="talk-room-comment" class="fas fa-comment-dots")
          p.fukidashi トーク
        span.tab-btn
          i(name="user-plus" id="talk-room-user-plus" class="fas fa-user-plus")
          p.fukidashi 友達追加
        span
          i(name="clock" id="talk-room-clock" class="fas fa-clock")
          p.fukidashi タイムライン
      .talk-room-index__sidebar--other
        span
          i(name="meeting" id="talk-room-meeting" class="fas fa-video")
          p.fukidashi ミーティング
        span
          i(name="capture" id="talk-room-capture" class="far fa-square")
          p.fukidashi 画面キャプチャ
        span
          i(name="keep" id="talk-room-keep" class="far fa-bookmark")
          p.fukidashi Keep
        span
          i(name="notifiction-off" id="talk-room-notifiction-off" class="fas fa-volume-down")
          p.fukidashi 全ての通知をオフ
        span
          i(name="other" id="talk-room-other" class="fas fa-ellipsis-h")
          p.other-fukidashi.fukidashi 設定
          .user-other
            = link_to '設定', edit_user_path(current_user.id), :onclick=>"window.open(this.href, '設定', 'height=470, width=660');return false;"
            = link_to 'ヘルプ', '#'
            = link_to 'LINE情報', '#', class: 'LINE'
            = link_to 'ログアウト', destroy_user_session_path, method: :delete
            = link_to '終了', '#'

    .talk-room-index__talk-rooms
      .talk-rooms.tab-content.is-show
        .talk-rooms__search
          = render partial: "layouts/search"
        .result
        .talk-rooms-content
          = link_to talk_rooms_path, class: "user-talk-show", remote: true do
            .talk-rooms__my-information
              .talk-rooms__my-information--image
                = render partial: "users/attachment", locals: { user: current_user}
              .talk-rooms__my-information--name
                p = current_user.name
          .talk-rooms__list
            .talk-rooms__list--groups
              span.select-group-list グループ
              ul
                - @entry_room.each do |room|
                  li class="group-room"
                    = link_to talk_rooms_path(room_id: room.id), class: "user-talk-show", remote: true do
                      - if room.talk_room_image.attached?
                        = image_tag(room.talk_room_image)
                      - else
                        = image_tag('room.png')
                      p = room.room_name
            .talk-rooms__list--friends
              span.select-friends-list 友だち
              ul
                - current_user.followings.includes(:followings).each do |follower|
                  li class="follower"
                    = link_to talk_rooms_path(follower: follower.id), class: "user-talk-show", remote: true do
                      = render partial: 'users/attachment', locals: { user: follower}
                      p = follower.name

      .talk.tab-content
        .talk__search
        .talk__friends
          ul.talk__friends--list
            / - if @latest_talks.present?
              - @latest_talks.each do |talk|
                - talk_user = talk.users.where.not(id: current_user.id)
                li class="latest_talk talk-room-#{talk.id}"
                  = link_to talk_rooms_path(follower: talk_user[0].id), class: "latest-talk-show", remote: true do
                    = render partial: 'users/attachment', locals: { user: talk_user[0]}
                    p.latest-talk-show__name-display
                      span.latest-talk-show__name-display--name = talk_user.last.name
                      span#latest-talk.latest-talk-show__name-display--display = talk.talk.last.talk
                    p.latest-talk-show__data-time-notifiction
                      span#data-time
                        / もしトークが今日の物ならば
                        - if Date.today == talk.talk.last.created_at.to_date
                          = talk.talk.last.created_at.strftime('%H:%M')
                        / もしトークが過去１週間ならば
                        - elsif 1.week.ago.beginning_of_day.to_date..Time.zone.now.end_of_day.to_date == talk.talk.last.created_at.to_date
                          - weeks = ["日","月","火","水","木","金","土"]
                          - num = talk.talk.last.created_at.strftime("%w").to_i
                          - week = weeks[num]
                          = week + "曜日"
                        / それ以降であれば
                        - else
                          = talk.talk.last.created_at.strftime("%Y.%M.%D")

      .add-friends.tab-content
        .add-friends__content
          .add-friends__content--search
            i.fas.fa-user-plus
            p 友だち検索
          .add-friends__content--create-group
            i.fas.fa-user-friends
            p = link_to 'グループ作成', new_talk_room_path, :onclick=>"window.open(this.href, 'グループ作成', 'height=500, width=450');return false;"
          .add-friends__content--create-open-chat
            i.far.fa-square
            p オープンチャット作成
        .add-friends__users
          .add-friends__users--official
            .official-account
              span.recommended-official おすすめ公式アカウント
              ul
          .add-friends__users--acquaintance
            .acquaintancers
              span.maybe-acquaintance 知り合いかも？
              ul
                - @users.each do |user|
                  - if user.followed_by?(current_user)
                  - else
                    li.acquaintance
                      = render partial: 'users/attachment', locals: { user: user}
                      p = user.name
                      = link_to user_relationships_path(user.id), method: :post do
                        i.fas.fa-user-plus
                        span.fukidashi 友だち追加

    .talk-room-index__talk
      .user-talks
        #talks.user-talks__talk
            = render partial: "users/user-talk-index", locals: { user: @user, room: @room, talks: @talks, room_name: @room_name}

app/views/talk_rooms/index.js.erb
$('#talks').html("<%= j(render partial: 'users/user-talk-index', locals: { user: @user, room: @room, talks: @talks, room_name: @room_name}) %>");

// 逆無限スクロール
$(document).ready(function(){
  let $talk = $('.user-talk-index__talks')

  // トーク内容の表示を一番下からに
  $talk.scrollTop(10000);

});

app/views/talk_rooms/new.html.slim
= form_with model: @talk_room, method: :post, local: true do |f|
  .create-new-talk-room
    .create-new-talk-room__top-wrapper
      .create-new-talk-room__top-wrapper--image
        = image_tag('room.png')
        #room-image-edit
          label.label
            i(name='image' id="create-room-image-icon" class="fas fa-camera")
            = f.file_field :talk_room_image, id: "create-room-image"
      .create-new-talk-room__top-wrapper--room-name
        = f.text_field :room_name, id: "create-room-name", :placeholder => "グループ名"

    .create-new-talk-room__choice-menber
      .create-new-talk-room__choice-menber--left
        .search-content
          .menber-search
            = render partial: "layouts/search"
        ul.menber-list
          - current_user.followings.includes(:followings).each do |follower|
            li class="follower"
              = render partial: 'users/attachment', locals: { user: follower}
              p = follower.name
              .follower-check
                = f.check_box :user_ids,{ multiple: true, checked: follower[:checked], disabled: follower[:disabled], include_hidden: false}, follower[:id]
      .create-new-talk-room__choice-menber--right
        #no-select-case
          p 選択した友達はいません。

    .create-new-talk-room__create-room
      .create-new-talk-room__create-room--btn
        .create-cancel
          = link_to "キャンセル", "#", id: "cancel"
        .create-success
          = f.submit "追加", id: "submit-room"

app/views/talk_rooms/show.html.slim
.talk-room-show
  / h2 = "#{@user.name} さんとのトーク"
  .talk-room-show__form
    input[type="text"
          id="talk-form"
          data-behavior="room_speaker"
          data-user="#{current_user.id}"
          data-room="#{@room.id}"]
  .talk-room-show__talks
    #talk
      - @talks.each do |talk|
        p = talk.talk