config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # ルートページ
  devise_for :users
  devise_scope :user do
    root :to => 'devise/sessions#new', as: :unauthenticated_root
  end

  # ユーザーアクション

  #検索機能
  get 'talkrooms/search', to: 'talk_rooms#search'

  #新規会員登録の時のルーティングエラーを修正
  get '/users', to: redirect("/user/sign_up")

  # ユーザー機能
  resources :users,             only: [:show, :edit, :update, :destroy] do
    resources :relationships,   only: [:create, :destroy]
    get :follows,   on: :member
    get :followers, on: :member
  end

  # 投稿機能
  resources :user_posts, only: [:new, :create, :index, :edit, :update, :destroy] do
    resources :post_comments, only: [:create, :update, :destroy]
  end

  # ルーム機能
  resources :talk_rooms do
    resources :room_media, only:  [:create, :update]
    resources :room_notes, only: [:create, :update, :destroy] do
      resources :room_note_media, only: [:create, :update]
    end
    resources :room_albums,     only: [:create, :update, :destroy]
    resources :room_events,     only: [:create, :update, :destroy]
    resource  :room_user,       only: [:index, :create, :destroy]
    resource  :room_favorites,  only: [:create, :destroy]
  end

  resources :talks,  only: [:create, :update]

  # 通知機能
  resources :notification, only: [:index]
end

app/models/user.rb
class User < ApplicationRecord

  validates :name, presence: true, length: { maximum: 20 }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         # authentication_keys: [:login]
  # include DeviseTokenAuth::Concerns::User

  validates :phone_number, presence: true, length: { in: 10..12 }, numericality: :only_integer

  has_one_attached :profile_image

  has_many :user_posts,       dependent: :destroy
  has_many :post_comments,    dependent: :destroy
  has_many :room_users,       dependent: :destroy
  has_many :talk,             dependent: :destroy
  has_many :room_mediums,     dependent: :destroy
  has_many :room_note,        dependent: :destroy
  has_many :room_note_mediums,dependent: :destroy
  has_many :room_albums,      dependent: :destroy
  has_many :room_favorites,   dependent: :destroy
  has_many :room_events,      dependent: :destroy

  # ユーザーは沢山のトークルームを持つ。それは他のユーザーを通してである。
  has_many :talk_room,        dependent: :destroy, through: :room_users

  # フォロー・フォロワーの情報を集める
  # has_many :relatinshipだと２通り書かなくてはならず名前被りが起こるので中間テーブル名を再定義する
  # =========== 自分がフォローしているユーザーとの関連 ==============
  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  has_many :followings, through: :active_relationships, source: :follower
  # ===========================================================
  # ============ 自分がフォローされるユーザーとの関連 ===============
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: :following
  # ===========================================================

  # 通知機能用の記述
  # 自分からの通知
  has_many  :active_notifications,  class_name: 'Notification',  foreign_key: 'visitor_id',  dependent: :destroy
  # 相手からの通知
  has_many  :passive_notifications, class_name: 'Notification',  foreign_key: 'visited_id',  dependent: :destroy

  # Userがfollow済みかどうか判定
  def followed_by?(user)
    passive_relationships.find_by(following_id: user.id).present?
  end

  # フォローされた時に通知がされるメソッド
  def create_notification_follow!(current_user)
    # 同じ通知レコードが存在しない時だけ、レコードを作成
    temp = Notification.where(["visitor_id = ? and Visited_id = ? and action = ? ", current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  def create
    # resource_params.keys.map(&:to_sym)は,送られてきたパラメータのkeyをチェックし、配列にします
    # 例えば値は[:password, :login]とかになります
    # resource_class.authentication_keysは、先程設定した認証のためのkeyで、つまり[:login]です
    # &でこの２つの積集合をとり、firstメソッドでその中身を取っています
    # つまりfield => :loginです
    field = (resource_params.keys.map(&:to_sym) & resource_class.authentication_keys).first
    @resource = nil

    if field
      q_value = get_case_insensitive_field_form_resource_params(field)

      @resource = find_resource(:email, q_value) if q_value.match?(/@/)
      @resource = find_resource(:phone_number, q_value) if q_value.match?(/\A\d{10}$|^\d{11}\z/)
    end

    if @resource && valid_params?(field, q_value) && (!@resource.respond_to?(:active_for_atuhentication?) || @resource.active_for_authentication?)
      valid_password = @resource.valid_password?(resource_params[:password])
      if (@resource.respond_to?(:valid_for_authentication?) && !@resource.valid_for_authentication? { valid_password}) || !valid_password
        return render_create_error_bad_credentials
      end
      @token = @resource.create_token
      @resource.save

      sign_in(:user, @resource, store: false, bypass: false)

      yield @resource if block_given?

      render_create_success
    elsif @resource && !(!@resource.respond_to?(:active_for_atuhentication?) || @resource.active_for_authentication?)
      if @resource.respond_to?(:locked_at) && @resource.locked_at
        render_create_error_account_loked
      else
        render_create_error_not_confirmed
      end
    else
      render_create_error_bad_credentials
    end
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected
  private

  def resource_params
    params.permit(:password, :login)
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    # ここからルームの分岐
    @current_room = RoomUser.where(user_id: current_user.id)
    @another_room = RoomUser.where(user_id: @user.id)
    unless @user.id == current_user.id
      @current_room.each do |cr|
        @another_room.each do |ar|
          # ルームが存在する時
          if cr.talk_room_id == ar.talk_room_id
            @is_room = true
            @room_id = cr.talk_room_id
          end
        end
      end
      # なければ新規作成
      unless @is_room
        @room = TalkRoom.new
        @room_user = RoomUser.new
      end
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_back(fallback_location: user_path(current_user))
  end

  def destroy
    # code
  end

  def follows
    user = User.find(params[:id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_attachment.html.slim
- if user.profile_image.attached?
  = image_tag(user.profile_image)
- else
  = image_tag('usagi.jpg') 

app/views/users/_user-talk-image.html.slim
#user-talk-image
  p
    - if talk.talk_image.present?
      = image_tag talk.talk_image

app/views/users/_user-talk-index.html.slim
- cache talks do
  .user-talk-index
    - unless user.blank? && room_name.blank?
      .user-talk-index__name
        - unless user.nil?
          p = "#{user.name}"
        - unless room_name.nil?
          p = "#{room_name}"
      .user-talk-index__talks
          div id="talk" data-user_id="#{current_user.id}"
            - unless talks.blank?
              - talks.includes(:user).each do |talk|
                - if talk.user_id == current_user.id
                  .user-talk-index__talks--right
                    .time
                      span = talk.created_at.strftime('%H:%M')
                    .talk = talk.talk
                - else
                  .user-talk-index__talks--left
                    - if talk.user.profile_image.attached?
                      = image_tag(talk.user.profile_image)
                    - else
                      = image_tag('usagi.jpg')
                    .talk = talk.talk
                    .time
                      span = talk.created_at.strftime('%H:%M')
      .user-talk-index__form
          textarea[type="text"
                    id="talk-form"
                    data-behavior="room_speaker"
                    data-user="#{current_user.id}"
                    data-room="#{room.id}"
                    placeholder="メッセージを入力"]
      .user-talk-index__file
          .user-talk-index__file--left
            label.label
              input[type="file"
                    id="send-file-form"
                    data-behavior="room_image"
                    data-user="#{current_user.id}"
                    data-room="#{room.id}"]
              i(name="send-file" id="user-talk-index-file" class="fas fa-paperclip")
            i(name="keep" id="user-talk-index-keep" class="far fa-bookmark")
            i(name="capture" id="user-talk-index-capture" class="far fa-square")
          .user-talk-index__file--right
            i(name="stamp" id="user-talk-index-stamp" class="far fa-smile")
    - else
        .non-talk-case
          .non-talk-case__contents
            img src="https://img.icons8.com/fluent-systems-filled/96/000000/line-me.png"
            span トークを始めよう！
            a href="https://icons8.com/icon/i7393ie24LoV/line" Line icon by Icons8

app/views/users/_user_talk.html.slim
- if talk.user_id == current_user.id
  .user-talk-index__talks--right
    .time
      span = talk.created_at.strftime("%H:%M")
    .talk = talk.talk
- else
  .user-talk-index__talks--left
    .name = talk.user.name
    .talk = talk.talk
    .time
      span = talk.created_at.strftime("%H:%M")

app/views/users/edit.html.slim
.content
  .user-edit
    .user-edit__sidebar
      = link_to '基本設定'
      = link_to '通知'
      = link_to 'トーク'
      = link_to '通話'
      = link_to '友達管理'
      = link_to 'Keep'
      = link_to '詳細設定'
      = link_to 'ショートカット'
      = link_to 'LINE情報'
    .user-edit__basic-set
      = form_with model: @user, method: :patch, local: true do |f|
        .user-edit__basic-set--top
          .image
            = render partial: "users/attachment", locals: { user: @user}
            #image-edit
              label.label
                i(name="image" id="user-edit-image-icon" class="fas fa-camera")
                = f.file_field :profile_image, id: "user-edit-image"
          .base
            .name
              p.left 名前
              = f.text_field :name, id: "user-edit-name", class: "right fa", :placeholder => "名前を入力　\uf304"
              = f.button(type="submit") do
                i.fas.fa-check
            .introduction
              p.left ステータスメッセージ
              = f.text_field :introduction, id: "user-edit-introduction", class: "right fa", :placeholder => "未設定　\uf304"
            .id
              p.left ID
            .mail
              p.left メール
              p.right = @user.email
            .other
              p.left その他
              .right
                = link_to '#' do
                  i.fas.fa-home
                  | ホーム
                span |
                = link_to '#' do
                  i.fas.fa-bookmark
                  | Keep
        .user-edit__basic-set--language
          p.language 言語
          .language-select
            span.language-select-placeholder 日本語
            ul
              li(data-value="en") English
              li(data-value="ja") 日本語
              li(data-value="kr") 한국
              li(data-value="hans") 简体中文
              li(data-value="hant") 繁體中文
              li(data-value="th") ประเทศไทย
              li(data-value="tr") Türkiye
              li(data-value="ru") Pусский
              li(data-value="id") Indonesia
              li(data-value="esa") Español - América Latina
              li(data-value="es") Español - España
            input(type="hidden" name="changeme")
        .user-edit__basic-set--font
          p.font フォント
          .font-select
            span.font-select-placeholder 既定フォント
        .user-edit__basic-set--login
          p.login ログイン
          = check_box_tag :sign_in
          = label_tag :sign_in, '自動ログイン'
        .user-edit__basic-set--screen
          p.screen-mode
            | 画面表示モード
            span.note 一部の画面ではダークモードを利用できません
          = check_box_tag :screen
          = label_tag :screen, 'システム設定と同期'

app/views/users/show.html.slim
p = @user.name
- unless @user.id == current_user.id
  - if @is_room == true
    = link_to "チャット", talk_room_path(@room_id ,user_id: @user.id)
  - else
    = form_with model: @room, url: talk_rooms_path, local: true do |f|
      = fields_for @room_user do |ru|
        = ru.hidden_field :user_id, value: @user.id
      = f.submit 'チャット'